Repository ucsb-cs156-s24/proj-courses-s24-4pm-1, pull requests merged in 2024-05, with the labels that each got.

#28 swagger option appears on SHOW_SWAGGER_UI_LINK
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: FixMe - Needs Peer CR, 5

#34 change default quarter to end qtr
  frontend/src/main/components/Quarters/SingleQuarterDropdown.js
  frontend/src/tests/components/Quarters/SingleQuarterDropdown.test.js
Labels: 10

#27 EN - Fixed Bug: Made "UCSB Courses Search" button appear clearly as button
  frontend/src/index.css
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/stories/components/Jobs/JobsTable.stories.mdx
  frontend/src/stories/components/Jobs/TestJobForm.stories.mdx
  frontend/src/stories/components/Utils/Plaintext.stories.mdx
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#30 Lm show h2console link
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: 5, FIXME-See CR, FIXME-Stalled

#37 allow partial pitest
  README.md
  pom.xml
Labels: 5

#39 fz-tabTitle
  frontend/public/index.html
  frontend/public/manifest.json
Labels: 5

#42 Create React Component for Grade Distribution History
  frontend/src/fixtures/gradeHistoryFixtures.js
  frontend/src/main/components/GradeHistory/GradeHistoryTable.js
  frontend/src/stories/components/GradeHistory/GradeHistory.stories.js
  frontend/src/tests/components/GradeHistory/GradeHistory.test.js
Labels: 10

#48 Add Grade History Table to Course Details Page
  frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsIndexPage.test.js
Labels: 10, Merge Candidate

#56 Add fixtures sort course
  frontend/src/fixtures/sectionFixtures.js
Labels: 5

#53 Added component/tests for Upload Grade History Job
  frontend/src/main/components/Jobs/JobComingSoon.js
  frontend/src/main/components/Jobs/UpdateGradeInfoJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/tests/components/Jobs/UpdateGradeInfoJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10

#58 Ruizhe - Add frontend part of delete button feature for personal sections table
  frontend/src/main/components/PersonalSections/PersonalSectionsTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesDetailsPage.js
  frontend/src/main/utils/sectionUtils.js
  frontend/src/tests/components/PersonalSections/PersonalSectionsTable.test.js
  frontend/src/tests/utils/sectionUtils.test.js
Labels: 10
